
language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-22.0.1
    - android-19
    - sys-img-armeabi-v7a-android-19
    - extra-android-m2repository

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - gradle wrapper -b wrapper.gradle
  - ./gradlew assembleDebugAndroidTest
  - android-wait-for-emulator

script:
  - ./gradlew test
  - adb shell input keyevent 82 &
  - ./gradlew cAT

addons:
  artifacts:
    paths:
      - ./build/reports
